# Gunakan image resmi Node.js sebagai dasar
FROM node:14

# Tentukan direktori kerja dalam container
WORKDIR /app

# Salin package.json dan package-lock.json (jika ada)
COPY package*.json ./

# Install dependensi Node.js
RUN npm install

# Salin semua file aplikasi ke dalam container
COPY . .

# Expose port yang digunakan oleh aplikasi
EXPOSE 3000

# Tentukan perintah untuk menjalankan aplikasi
CMD ["npm", "start"]
