version: '3'
services:
  db:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: npm start
    volumes: 
        - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      POSTGRES_DB: employee-management
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: employee123
