version: '3'
services:
  db:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5432:5432"
  app:
    build:
      context: .
      dockerfile: Dockerfile-app
    command: npm start
    volumes: 
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
